In [2]:
import pandas as pd

pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv("google-play-store-apps-ratings-reviews.csv")

In [6]:
rows, cols = df.shape
print(f"rows = {rows}, cols ={cols}")

rows = 1200, cols =12

In [7]:
df.head()

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
0,App_1,HEALTH,3.7,401077,2.5,"1,000,000+",Paid,1.99,Teen,Education,2024-06-05,8.0 and up
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
2,App_3,ENTERTAINMENT,2.5,4989914,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-06-12,5.0 and up
3,App_4,TOOLS,3.0,1004011,2.5,"1,000+",Free,0.00,Everyone,Action,2024-05-26,4.1 and up
4,App_5,HEALTH,3.5,312033,2.5,"1,000,000+",Free,2.99,Everyone,Health,2024-06-02,4.1 and up

In [8]:
df.sample(5)

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1133,App_1134,HEALTH,3.4,4718794,2.5,"10,000,000+",Free,0.00,Everyone,Health,2024-11-23,4.1 and up
1171,App_1172,EDUCATION,3.6,3201218,2.5,"100,000+",Paid,0.99,Mature 17+,Tools,2024-01-21,5.0 and up
180,App_181,FINANCE,3.6,828801,2.5,"10,000+",Free,1.99,Everyone,Music,2024-07-04,4.1 and up
572,App_573,BUSINESS,3.6,3877819,2.5,"10,000+",Free,0.00,Mature 17+,Business,2024-08-05,4.1 and up
719,App_720,EDUCATION,4.1,2363138,2.5,"10,000,000+",Free,1.99,Teen,Tools,2024-12-13,5.0 and up

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              1200 non-null   str
 1   Category         1200 non-null   str
 2   Rating           1200 non-null   float64
 3   Reviews          1200 non-null   int64
 4   Size_MB          1200 non-null   float64
 5   Installs         1200 non-null   str
 6   Type             1200 non-null   str
 7   Price_$          1200 non-null   float64
 8   Content_Rating   1200 non-null   str
 9   Genres           1200 non-null   str
 10  Last_Updated     1200 non-null   str
 11  Android_Version  1200 non-null   str
dtypes: float64(3), int64(1), str(8)
memory usage: 112.6 KB

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Rating,1200.0,3.735500e+00,7.259676e-01,2.5,3.10,3.70,4.40,5.00
Reviews,1200.0,2.494315e+06,1.453801e+06,4148.0,1280934.50,2467298.50,3766748.25,4999121.00
Size_MB,1200.0,2.500000e+00,0.000000e+00,2.5,2.50,2.50,2.50,2.50
Price_$,1200.0,2.148583e+00,1.702337e+00,0.0,0.99,1.99,2.99,4.99

In [12]:
df.describe(include="str").T

                count unique         top  freq
App              1200   1200       App_1     1
Category         1200      9        GAME   158
Installs         1200      5  1,000,000+   260
Type             1200      2        Free  1017
Content_Rating   1200      3    Everyone   415
Genres           1200      7      Action   209
Last_Updated     1200    349  2024-08-08     9
Android_Version  1200      4  8.0 and up   333

In [14]:
df['Genres'].unique()

<StringArray>
['Education', 'Health', 'Action', 'Music', 'Tools', 'Puzzle', 'Business']
Length: 7, dtype: str

In [18]:
df.sort_values('Genres', ascending=False)["Genres"].value_counts()

Genres
Action       209
Music        185
Education    175
Tools        169
Puzzle       156
Business     155
Health       151
Name: count, dtype: int64

In [19]:
df[["App", "Rating", "Reviews", "Installs", "Genres"]]

           App  Rating  Reviews     Installs     Genres
0        App_1     3.7   401077   1,000,000+  Education
1        App_2     5.0   460806      10,000+  Education
2        App_3     2.5  4989914  10,000,000+     Health
3        App_4     3.0  1004011       1,000+     Action
4        App_5     3.5   312033   1,000,000+     Health
...        ...     ...      ...          ...        ...
1195  App_1196     3.2  2367332  10,000,000+     Health
1196  App_1197     4.5  1375655  10,000,000+   Business
1197  App_1198     3.9  3738868       1,000+     Health
1198  App_1199     4.1  2270473      10,000+     Puzzle
1199  App_1200     3.1   834450      10,000+      Tools

[1200 rows x 5 columns]

In [20]:
df.iloc[:10, :]

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
0,App_1,HEALTH,3.7,401077,2.5,"1,000,000+",Paid,1.99,Teen,Education,2024-06-05,8.0 and up
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
2,App_3,ENTERTAINMENT,2.5,4989914,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-06-12,5.0 and up
3,App_4,TOOLS,3.0,1004011,2.5,"1,000+",Free,0.00,Everyone,Action,2024-05-26,4.1 and up
4,App_5,HEALTH,3.5,312033,2.5,"1,000,000+",Free,2.99,Everyone,Health,2024-06-02,4.1 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
6,App_7,HEALTH,2.7,4686176,2.5,"10,000+",Free,4.99,Everyone,Music,2024-05-10,6.0 and up
7,App_8,ENTERTAINMENT,2.5,3177912,2.5,"10,000+",Paid,4.99,Mature 17+,Health,2024-12-23,6.0 and up
8,App_9,TOOLS,2.6,755121,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-09-11,8.0 and up
9,App_10,LIFESTYLE,2.7,2320725,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-07-26,6.0 and up

In [22]:
df.loc[:9, ["App", "Rating", "Installs"]]

      App  Rating     Installs
0   App_1     3.7   1,000,000+
1   App_2     5.0      10,000+
2   App_3     2.5  10,000,000+
3   App_4     3.0       1,000+
4   App_5     3.5   1,000,000+
5   App_6     4.8       1,000+
6   App_7     2.7      10,000+
7   App_8     2.5      10,000+
8   App_9     2.6  10,000,000+
9  App_10     2.7  10,000,000+

In [25]:
high_rating_apps = df[df["Rating"] > 4.4]
high_rating_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
22,App_23,PRODUCTIVITY,4.6,4747405,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-04-02,5.0 and up
26,App_27,LIFESTYLE,4.8,3045925,2.5,"10,000,000+",Free,0.99,Everyone,Action,2024-06-06,8.0 and up
31,App_32,HEALTH,4.9,1034596,2.5,"10,000,000+",Free,2.99,Mature 17+,Action,2024-08-09,8.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,App_1186,EDUCATION,4.7,3913407,2.5,"10,000+",Free,0.99,Everyone,Tools,2024-02-23,8.0 and up
1186,App_1187,TOOLS,4.7,3088599,2.5,"1,000+",Free,1.99,Mature 17+,Puzzle,2024-12-07,8.0 and up
1189,App_1190,HEALTH,5.0,1862215,2.5,"10,000+",Free,4.99,Teen,Action,2024-01-06,8.0 and up
1192,App_1193,GAME,4.6,1706836,2.5,"1,000,000+",Free,1.99,Mature 17+,Action,2024-12-11,5.0 and up
1196,App_1197,BUSINESS,4.5,1375655,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-08-19,8.0 and up

In [28]:
high_rating_and_free_apps = df[(df["Rating"] > 4.4) & (df["Type"] == "Free")]
high_rating_and_free_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
22,App_23,PRODUCTIVITY,4.6,4747405,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-04-02,5.0 and up
26,App_27,LIFESTYLE,4.8,3045925,2.5,"10,000,000+",Free,0.99,Everyone,Action,2024-06-06,8.0 and up
31,App_32,HEALTH,4.9,1034596,2.5,"10,000,000+",Free,2.99,Mature 17+,Action,2024-08-09,8.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,App_1186,EDUCATION,4.7,3913407,2.5,"10,000+",Free,0.99,Everyone,Tools,2024-02-23,8.0 and up
1186,App_1187,TOOLS,4.7,3088599,2.5,"1,000+",Free,1.99,Mature 17+,Puzzle,2024-12-07,8.0 and up
1189,App_1190,HEALTH,5.0,1862215,2.5,"10,000+",Free,4.99,Teen,Action,2024-01-06,8.0 and up
1192,App_1193,GAME,4.6,1706836,2.5,"1,000,000+",Free,1.99,Mature 17+,Action,2024-12-11,5.0 and up
1196,App_1197,BUSINESS,4.5,1375655,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-08-19,8.0 and up

In [29]:
high_rating_and_free_apps[["App", "Rating"]]

           App  Rating
1        App_2     5.0
5        App_6     4.8
22      App_23     4.6
26      App_27     4.8
31      App_32     4.9
...        ...     ...
1185  App_1186     4.7
1186  App_1187     4.7
1189  App_1190     5.0
1192  App_1193     4.6
1196  App_1197     4.5

[222 rows x 2 columns]

In [30]:
new_df = df[(df["Rating"] > 4.4) & (df["Reviews"] > 100_000)]
new_df

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
22,App_23,PRODUCTIVITY,4.6,4747405,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-04-02,5.0 and up
26,App_27,LIFESTYLE,4.8,3045925,2.5,"10,000,000+",Free,0.99,Everyone,Action,2024-06-06,8.0 and up
31,App_32,HEALTH,4.9,1034596,2.5,"10,000,000+",Free,2.99,Mature 17+,Action,2024-08-09,8.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,App_1186,EDUCATION,4.7,3913407,2.5,"10,000+",Free,0.99,Everyone,Tools,2024-02-23,8.0 and up
1186,App_1187,TOOLS,4.7,3088599,2.5,"1,000+",Free,1.99,Mature 17+,Puzzle,2024-12-07,8.0 and up
1189,App_1190,HEALTH,5.0,1862215,2.5,"10,000+",Free,4.99,Teen,Action,2024-01-06,8.0 and up
1192,App_1193,GAME,4.6,1706836,2.5,"1,000,000+",Free,1.99,Mature 17+,Action,2024-12-11,5.0 and up
1196,App_1197,BUSINESS,4.5,1375655,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-08-19,8.0 and up

In [31]:
new_df2 = df[(df["Rating"] == 5.0) | (df["Reviews"] > 1_000_000)]
new_df2

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
2,App_3,ENTERTAINMENT,2.5,4989914,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-06-12,5.0 and up
3,App_4,TOOLS,3.0,1004011,2.5,"1,000+",Free,0.00,Everyone,Action,2024-05-26,4.1 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
6,App_7,HEALTH,2.7,4686176,2.5,"10,000+",Free,4.99,Everyone,Music,2024-05-10,6.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1194,App_1195,FINANCE,3.6,1441256,2.5,"10,000+",Free,0.00,Everyone,Music,2024-03-13,5.0 and up
1195,App_1196,PRODUCTIVITY,3.2,2367332,2.5,"10,000,000+",Free,2.99,Mature 17+,Health,2024-06-22,4.1 and up
1196,App_1197,BUSINESS,4.5,1375655,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-08-19,8.0 and up
1197,App_1198,GAME,3.9,3738868,2.5,"1,000+",Paid,1.99,Everyone,Health,2024-09-26,6.0 and up
1198,App_1199,BUSINESS,4.1,2270473,2.5,"10,000+",Paid,1.99,Everyone,Puzzle,2024-12-27,4.1 and up

In [32]:
df.sort_values("Rating", ascending=False).head(10)

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
39,App_40,PRODUCTIVITY,5.0,3021382,2.5,"1,000+",Paid,1.99,Mature 17+,Education,2024-02-18,8.0 and up
35,App_36,BUSINESS,5.0,3672287,2.5,"10,000,000+",Free,4.99,Everyone,Health,2024-09-07,5.0 and up
914,App_915,HEALTH,5.0,2716217,2.5,"1,000,000+",Free,1.99,Everyone,Health,2024-04-09,8.0 and up
88,App_89,ENTERTAINMENT,5.0,1520992,2.5,"10,000,000+",Free,0.00,Teen,Health,2024-08-28,5.0 and up
756,App_757,FINANCE,5.0,4445828,2.5,"100,000+",Free,1.99,Teen,Education,2024-06-03,4.1 and up
744,App_745,HEALTH,5.0,3281951,2.5,"10,000+",Free,1.99,Mature 17+,Puzzle,2024-05-23,4.1 and up
995,App_996,ENTERTAINMENT,5.0,853339,2.5,"10,000,000+",Paid,0.99,Mature 17+,Business,2024-03-30,8.0 and up
802,App_803,EDUCATION,5.0,1661665,2.5,"100,000+",Free,1.99,Mature 17+,Business,2024-09-02,5.0 and up
895,App_896,LIFESTYLE,5.0,1011940,2.5,"1,000+",Free,4.99,Mature 17+,Music,2024-12-01,6.0 and up

In [33]:
df.sort_values("Reviews", ascending=False).head(10)

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
747,App_748,HEALTH,2.6,4999121,2.5,"10,000+",Paid,0.00,Teen,Tools,2024-06-21,8.0 and up
1131,App_1132,ENTERTAINMENT,4.7,4996556,2.5,"10,000+",Free,0.99,Mature 17+,Tools,2024-09-12,8.0 and up
497,App_498,LIFESTYLE,3.6,4995939,2.5,"10,000,000+",Paid,1.99,Everyone,Puzzle,2024-03-28,6.0 and up
971,App_972,EDUCATION,4.3,4991197,2.5,"1,000,000+",Free,2.99,Mature 17+,Action,2024-09-15,8.0 and up
2,App_3,ENTERTAINMENT,2.5,4989914,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-06-12,5.0 and up
911,App_912,TOOLS,3.7,4982052,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-03-23,8.0 and up
1077,App_1078,PRODUCTIVITY,2.8,4980147,2.5,"100,000+",Free,1.99,Everyone,Business,2024-12-07,8.0 and up
96,App_97,ENTERTAINMENT,4.7,4975240,2.5,"1,000,000+",Free,2.99,Mature 17+,Music,2024-05-17,4.1 and up
117,App_118,HEALTH,2.5,4975055,2.5,"1,000,000+",Free,1.99,Mature 17+,Tools,2024-01-21,4.1 and up
1052,App_1053,GAME,3.0,4969421,2.5,"1,000,000+",Free,4.99,Mature 17+,Health,2024-01-19,8.0 and up

In [35]:
df.sort_values("Rating", ascending=False).head(1)

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up

In [36]:
highest_rating = df["Rating"].max()
highest_rating_apps = df[df["Rating"] == highest_rating]
highest_rating_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
35,App_36,BUSINESS,5.0,3672287,2.5,"10,000,000+",Free,4.99,Everyone,Health,2024-09-07,5.0 and up
39,App_40,PRODUCTIVITY,5.0,3021382,2.5,"1,000+",Paid,1.99,Mature 17+,Education,2024-02-18,8.0 and up
61,App_62,PRODUCTIVITY,5.0,2233716,2.5,"10,000,000+",Free,0.99,Teen,Action,2024-07-22,6.0 and up
88,App_89,ENTERTAINMENT,5.0,1520992,2.5,"10,000,000+",Free,0.00,Teen,Health,2024-08-28,5.0 and up
148,App_149,GAME,5.0,2179441,2.5,"10,000,000+",Paid,0.00,Everyone,Health,2024-11-21,5.0 and up
215,App_216,PRODUCTIVITY,5.0,2762091,2.5,"10,000,000+",Free,1.99,Everyone,Puzzle,2024-09-10,8.0 and up
311,App_312,HEALTH,5.0,1038346,2.5,"1,000+",Free,0.00,Teen,Music,2024-12-16,8.0 and up
365,App_366,FINANCE,5.0,562631,2.5,"10,000,000+",Free,4.99,Mature 17+,Health,2024-08-16,4.1 and up
420,App_421,TOOLS,5.0,2076485,2.5,"10,000+",Free,1.99,Everyone,Action,2024-09-30,6.0 and up
571,App_572,GAME,5.0,1751508,2.5,"1,000+",Paid,4.99,Teen,Action,2024-09-03,5.0 and up
585,App_586,FINANCE,5.0,2921999,2.5,"10,000,000+",Paid,2.99,Teen,Education,2024-03-14,6.0 and up
744,App_745,HEALTH,5.0,3281951,2.5,"10,000+",Free,1.99,Mature 17+,Puzzle,2024-05-23,4.1 and up
756,App_757,FINANCE,5.0,4445828,2.5,"100,000+",Free,1.99,Teen,Education,2024-06-03,4.1 and up
802,App_803,EDUCATION,5.0,1661665,2.5,"100,000+",Free,1.99,Mature 17+,Business,2024-09-02,5.0 and up
895,App_896,LIFESTYLE,5.0,1011940,2.5,"1,000+",Free,4.99,Mature 17+,Music,2024-12-01,6.0 and up
914,App_915,HEALTH,5.0,2716217,2.5,"1,000,000+",Free,1.99,Everyone,Health,2024-04-09,8.0 and up
995,App_996,ENTERTAINMENT,5.0,853339,2.5,"10,000,000+",Paid,0.99,Mature 17+,Business,2024-03-30,8.0 and up
1075,App_1076,GAME,5.0,2163359,2.5,"10,000+",Paid,2.99,Everyone,Business,2024-06-04,4.1 and up
1080,App_1081,TOOLS,5.0,3891161,2.5,"10,000+",Free,0.99,Mature 17+,Puzzle,2024-08-23,5.0 and up
1096,App_1097,TOOLS,5.0,1520383,2.5,"10,000,000+",Free,0.00,Mature 17+,Action,2024-08-09,8.0 and up
1127,App_1128,ENTERTAINMENT,5.0,2431002,2.5,"10,000,000+",Free,2.99,Everyone,Action,2024-01-13,8.0 and up
1165,App_1166,TOOLS,5.0,2436841,2.5,"100,000+",Free,0.99,Teen,Tools,2024-04-11,8.0 and up
1189,App_1190,HEALTH,5.0,1862215,2.5,"10,000+",Free,4.99,Teen,Action,2024-01-06,8.0 and up

In [37]:
high_rating = 4.4
high_number_of_reviews = 3_750_000

In [39]:
df["Genres"].value_counts()

Genres
Action       209
Music        185
Education    175
Tools        169
Puzzle       156
Business     155
Health       151
Name: count, dtype: int64

In [40]:
df[(df['Type'] == "Free") & (df['Rating'] > high_rating) & (df['Reviews'] > high_number_of_reviews)]

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
22,App_23,PRODUCTIVITY,4.6,4747405,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-04-02,5.0 and up
50,App_51,LIFESTYLE,4.9,4396730,2.5,"10,000+",Free,0.00,Everyone,Action,2024-11-15,5.0 and up
51,App_52,BUSINESS,4.6,4070038,2.5,"1,000,000+",Free,4.99,Mature 17+,Business,2024-09-25,5.0 and up
85,App_86,PRODUCTIVITY,4.9,3804419,2.5,"10,000+",Free,4.99,Mature 17+,Action,2024-05-09,6.0 and up
96,App_97,ENTERTAINMENT,4.7,4975240,2.5,"1,000,000+",Free,2.99,Mature 17+,Music,2024-05-17,4.1 and up
110,App_111,GAME,4.9,4450262,2.5,"100,000+",Free,4.99,Everyone,Health,2024-05-04,6.0 and up
128,App_129,GAME,4.5,4415286,2.5,"10,000,000+",Free,4.99,Mature 17+,Health,2024-09-27,5.0 and up
177,App_178,TOOLS,4.6,4701679,2.5,"1,000,000+",Free,2.99,Teen,Business,2024-11-14,5.0 and up
178,App_179,LIFESTYLE,4.9,3765066,2.5,"1,000+",Free,0.00,Everyone,Business,2024-03-27,6.0 and up
186,App_187,LIFESTYLE,4.7,3878460,2.5,"1,000+",Free,0.99,Everyone,Action,2024-04-02,6.0 and up
224,App_225,GAME,4.9,4093896,2.5,"10,000,000+",Free,4.99,Mature 17+,Health,2024-11-19,8.0 and up
241,App_242,EDUCATION,4.6,4022938,2.5,"1,000,000+",Free,0.99,Mature 17+,Action,2024-06-15,5.0 and up
250,App_251,ENTERTAINMENT,4.9,4588737,2.5,"1,000,000+",Free,0.00,Everyone,Health,2024-11-19,5.0 and up
257,App_258,HEALTH,4.8,4232949,2.5,"1,000,000+",Free,1.99,Mature 17+,Puzzle,2024-12-19,5.0 and up
279,App_280,ENTERTAINMENT,4.7,4161910,2.5,"10,000+",Free,2.99,Teen,Puzzle,2024-04-22,4.1 and up
297,App_298,HEALTH,4.6,4836927,2.5,"1,000+",Free,2.99,Teen,Tools,2024-06-19,6.0 and up
400,App_401,GAME,4.9,4275125,2.5,"1,000,000+",Free,0.99,Teen,Action,2024-09-07,4.1 and up
409,App_410,EDUCATION,4.8,3930020,2.5,"1,000+",Free,0.00,Everyone,Health,2024-04-30,6.0 and up
411,App_412,EDUCATION,4.9,4079451,2.5,"1,000,000+",Free,1.99,Everyone,Music,2024-04-02,6.0 and up
455,App_456,PRODUCTIVITY,4.5,3852266,2.5,"10,000+",Free,4.99,Teen,Action,2024-12-22,4.1 and up
470,App_471,PRODUCTIVITY,4.9,4510794,2.5,"1,000,000+",Free,0.00,Everyone,Action,2024-07-29,6.0 and up
491,App_492,GAME,4.5,4510589,2.5,"10,000+",Free,0.99,Mature 17+,Action,2024-09-11,8.0 and up
519,App_520,TOOLS,4.5,4176436,2.5,"10,000,000+",Free,1.99,Everyone,Action,2024-05-29,5.0 and up
589,App_590,FINANCE,4.9,4943092,2.5,"1,000+",Free,0.99,Teen,Music,2024-05-07,5.0 and up
612,App_613,EDUCATION,4.9,4490522,2.5,"10,000+",Free,4.99,Mature 17+,Health,2024-10-12,4.1 and up
613,App_614,BUSINESS,4.7,4944500,2.5,"1,000,000+",Free,0.99,Everyone,Health,2024-07-03,8.0 and up
642,App_643,LIFESTYLE,4.6,4262637,2.5,"10,000,000+",Free,4.99,Mature 17+,Action,2024-05-14,6.0 and up
645,App_646,GAME,4.6,4301410,2.5,"1,000,000+",Free,0.00,Mature 17+,Education,2024-01-19,6.0 and up
656,App_657,HEALTH,4.7,4062234,2.5,"1,000+",Free,2.99,Everyone,Education,2024-07-09,4.1 and up
674,App_675,FINANCE,4.5,4584084,2.5,"10,000,000+",Free,0.99,Mature 17+,Puzzle,2024-08-02,8.0 and up
685,App_686,GAME,4.6,3844896,2.5,"10,000,000+",Free,4.99,Everyone,Business,2024-08-11,8.0 and up
740,App_741,FINANCE,4.7,4411897,2.5,"10,000,000+",Free,0.00,Teen,Business,2024-07-03,8.0 and up
756,App_757,FINANCE,5.0,4445828,2.5,"100,000+",Free,1.99,Teen,Education,2024-06-03,4.1 and up
757,App_758,BUSINESS,4.9,4095087,2.5,"10,000+",Free,4.99,Teen,Music,2024-06-23,5.0 and up
759,App_760,LIFESTYLE,4.5,4630242,2.5,"1,000,000+",Free,0.00,Everyone,Business,2024-04-24,5.0 and up
768,App_769,ENTERTAINMENT,4.7,4023288,2.5,"100,000+",Free,0.99,Mature 17+,Tools,2024-04-02,4.1 and up
805,App_806,BUSINESS,4.7,4789135,2.5,"1,000,000+",Free,1.99,Mature 17+,Health,2024-07-05,8.0 and up
848,App_849,FINANCE,4.5,4457345,2.5,"100,000+",Free,1.99,Mature 17+,Business,2024-02-22,4.1 and up
855,App_856,LIFESTYLE,4.6,3754552,2.5,"100,000+",Free,0.99,Teen,Action,2024-03-28,6.0 and up
959,App_960,FINANCE,4.6,3861784,2.5,"1,000,000+",Free,2.99,Mature 17+,Tools,2024-11-09,4.1 and up
962,App_963,GAME,4.6,4327812,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-05-19,6.0 and up
1067,App_1068,TOOLS,4.6,3905523,2.5,"100,000+",Free,2.99,Teen,Action,2024-02-08,8.0 and up
1071,App_1072,LIFESTYLE,4.6,4318430,2.5,"10,000+",Free,0.99,Teen,Music,2024-06-18,6.0 and up
1080,App_1081,TOOLS,5.0,3891161,2.5,"10,000+",Free,0.99,Mature 17+,Puzzle,2024-08-23,5.0 and up
1090,App_1091,GAME,4.9,4703865,2.5,"1,000,000+",Free,0.99,Mature 17+,Tools,2024-04-17,5.0 and up
1116,App_1117,LIFESTYLE,4.5,4798803,2.5,"10,000+",Free,4.99,Everyone,Action,2024-08-12,5.0 and up
1117,App_1118,EDUCATION,4.6,4184248,2.5,"1,000+",Free,0.99,Mature 17+,Education,2024-10-12,6.0 and up
1131,App_1132,ENTERTAINMENT,4.7,4996556,2.5,"10,000+",Free,0.99,Mature 17+,Tools,2024-09-12,8.0 and up
1161,App_1162,PRODUCTIVITY,4.9,4756007,2.5,"1,000+",Free,2.99,Everyone,Action,2024-11-29,4.1 and up
1164,App_1165,HEALTH,4.6,3973323,2.5,"10,000,000+",Free,0.99,Mature 17+,Music,2024-03-07,8.0 and up
1179,App_1180,BUSINESS,4.6,4637213,2.5,"100,000+",Free,0.99,Mature 17+,Tools,2024-03-17,6.0 and up
1185,App_1186,EDUCATION,4.7,3913407,2.5,"10,000+",Free,0.99,Everyone,Tools,2024-02-23,8.0 and up

In [46]:
high_rated_apps = df.loc[df["Rating"] >= 4.5]
high_rated_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
22,App_23,PRODUCTIVITY,4.6,4747405,2.5,"10,000,000+",Free,0.00,Mature 17+,Tools,2024-04-02,5.0 and up
26,App_27,LIFESTYLE,4.8,3045925,2.5,"10,000,000+",Free,0.99,Everyone,Action,2024-06-06,8.0 and up
31,App_32,HEALTH,4.9,1034596,2.5,"10,000,000+",Free,2.99,Mature 17+,Action,2024-08-09,8.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1185,App_1186,EDUCATION,4.7,3913407,2.5,"10,000+",Free,0.99,Everyone,Tools,2024-02-23,8.0 and up
1186,App_1187,TOOLS,4.7,3088599,2.5,"1,000+",Free,1.99,Mature 17+,Puzzle,2024-12-07,8.0 and up
1189,App_1190,HEALTH,5.0,1862215,2.5,"10,000+",Free,4.99,Teen,Action,2024-01-06,8.0 and up
1192,App_1193,GAME,4.6,1706836,2.5,"1,000,000+",Free,1.99,Mature 17+,Action,2024-12-11,5.0 and up
1196,App_1197,BUSINESS,4.5,1375655,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-08-19,8.0 and up

In [47]:
low_rated_apps = df.loc[df["Rating"] < 4.0]
low_rated_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
0,App_1,HEALTH,3.7,401077,2.5,"1,000,000+",Paid,1.99,Teen,Education,2024-06-05,8.0 and up
2,App_3,ENTERTAINMENT,2.5,4989914,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-06-12,5.0 and up
3,App_4,TOOLS,3.0,1004011,2.5,"1,000+",Free,0.00,Everyone,Action,2024-05-26,4.1 and up
4,App_5,HEALTH,3.5,312033,2.5,"1,000,000+",Free,2.99,Everyone,Health,2024-06-02,4.1 and up
6,App_7,HEALTH,2.7,4686176,2.5,"10,000+",Free,4.99,Everyone,Music,2024-05-10,6.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1193,App_1194,LIFESTYLE,3.2,2059395,2.5,"10,000+",Free,1.99,Teen,Business,2024-09-17,6.0 and up
1194,App_1195,FINANCE,3.6,1441256,2.5,"10,000+",Free,0.00,Everyone,Music,2024-03-13,5.0 and up
1195,App_1196,PRODUCTIVITY,3.2,2367332,2.5,"10,000,000+",Free,2.99,Mature 17+,Health,2024-06-22,4.1 and up
1197,App_1198,GAME,3.9,3738868,2.5,"1,000+",Paid,1.99,Everyone,Health,2024-09-26,6.0 and up
1199,App_1200,HEALTH,3.1,834450,2.5,"10,000+",Free,0.00,Everyone,Tools,2024-08-09,6.0 and up

In [48]:
high_rated_apps["Reviews"].mean()

np.float64(2420019.023076923)

In [50]:
high_rated_apps["Reviews"].median()

np.float64(2353470.0)

In [52]:
high_rated_apps["Reviews"].std()

np.float64(1398192.6526831633)

In [49]:
low_rated_apps["Reviews"].mean()

np.float64(2477444.507204611)

In [51]:
low_rated_apps["Reviews"].median()

np.float64(2377227.0)

In [53]:
low_rated_apps["Reviews"].std()

np.float64(1481450.5197666206)

In [54]:
free_apps = df.loc[df["Type"] == "Free"]
free_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
1,App_2,LIFESTYLE,5.0,460806,2.5,"10,000+",Free,0.99,Mature 17+,Education,2024-09-14,8.0 and up
2,App_3,ENTERTAINMENT,2.5,4989914,2.5,"10,000,000+",Free,2.99,Teen,Health,2024-06-12,5.0 and up
3,App_4,TOOLS,3.0,1004011,2.5,"1,000+",Free,0.00,Everyone,Action,2024-05-26,4.1 and up
4,App_5,HEALTH,3.5,312033,2.5,"1,000,000+",Free,2.99,Everyone,Health,2024-06-02,4.1 and up
5,App_6,EDUCATION,4.8,3205609,2.5,"1,000+",Free,0.00,Teen,Health,2024-02-07,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1193,App_1194,LIFESTYLE,3.2,2059395,2.5,"10,000+",Free,1.99,Teen,Business,2024-09-17,6.0 and up
1194,App_1195,FINANCE,3.6,1441256,2.5,"10,000+",Free,0.00,Everyone,Music,2024-03-13,5.0 and up
1195,App_1196,PRODUCTIVITY,3.2,2367332,2.5,"10,000,000+",Free,2.99,Mature 17+,Health,2024-06-22,4.1 and up
1196,App_1197,BUSINESS,4.5,1375655,2.5,"10,000,000+",Free,0.99,Teen,Business,2024-08-19,8.0 and up
1199,App_1200,HEALTH,3.1,834450,2.5,"10,000+",Free,0.00,Everyone,Tools,2024-08-09,6.0 and up

In [55]:
paid_apps = df.loc[df["Type"] == "Paid"]
paid_apps

,App,Category,Rating,Reviews,Size_MB,Installs,Type,Price_$,Content_Rating,Genres,Last_Updated,Android_Version
0,App_1,HEALTH,3.7,401077,2.5,"1,000,000+",Paid,1.99,Teen,Education,2024-06-05,8.0 and up
7,App_8,ENTERTAINMENT,2.5,3177912,2.5,"10,000+",Paid,4.99,Mature 17+,Health,2024-12-23,6.0 and up
11,App_12,ENTERTAINMENT,3.7,4304469,2.5,"1,000,000+",Paid,0.99,Mature 17+,Tools,2024-12-13,5.0 and up
13,App_14,FINANCE,3.2,3457560,2.5,"100,000+",Paid,0.99,Mature 17+,Puzzle,2024-06-19,6.0 and up
23,App_24,GAME,4.3,2770752,2.5,"10,000+",Paid,1.99,Teen,Puzzle,2024-10-26,5.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
1171,App_1172,EDUCATION,3.6,3201218,2.5,"100,000+",Paid,0.99,Mature 17+,Tools,2024-01-21,5.0 and up
1175,App_1176,BUSINESS,3.2,2848893,2.5,"10,000+",Paid,4.99,Teen,Health,2024-08-22,5.0 and up
1183,App_1184,EDUCATION,4.0,3649254,2.5,"10,000,000+",Paid,0.00,Everyone,Health,2024-07-31,8.0 and up
1197,App_1198,GAME,3.9,3738868,2.5,"1,000+",Paid,1.99,Everyone,Health,2024-09-26,6.0 and up
1198,App_1199,BUSINESS,4.1,2270473,2.5,"10,000+",Paid,1.99,Everyone,Puzzle,2024-12-27,4.1 and up

In [56]:
free_apps["Rating"].mean()

np.float64(3.7421828908554575)

In [57]:
paid_apps["Rating"].mean()

np.float64(3.6983606557377047)

In [59]:
high_rated_apps["Genres"].value_counts()

Genres
Action       59
Tools        43
Education    34
Health       34
Music        34
Puzzle       29
Business     27
Name: count, dtype: int64

In [60]:
df.isnull().sum()

App                0
Category           0
Rating             0
Reviews            0
Size_MB            0
Installs           0
Type               0
Price_$            0
Content_Rating     0
Genres             0
Last_Updated       0
Android_Version    0
dtype: int64

In [61]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size_MB, Installs, Type, Price_$, Content_Rating, Genres, Last_Updated, Android_Version]
Index: []

In [62]:
clean_df = df.dropna()

In [63]:
clean_df.isnull().sum()

App                0
Category           0
Rating             0
Reviews            0
Size_MB            0
Installs           0
Type               0
Price_$            0
Content_Rating     0
Genres             0
Last_Updated       0
Android_Version    0
dtype: int64

In [64]:
clean_df.to_csv("google_play_cleaned.csv", index=False)